# Basic Makefile, created on Sunday, 09 September 2001 at 09:49:44 BST.
#
# Note that the standard Makefile rules and defines have been moved to
# the file below.

ELKSDIR		= ..

#########################################################################
# Include standard rules.

include $(ELKSDIR)/Makefile-rules

#########################################################################
### Dependencies:
