.TH ps 1 "ELKS System Utilities" "ELKS" \" -*- nroff -*-
.SH NAME
ps \- list processes
.SH SYNOPSIS
.B ps
.SH DESCRIPTION
.BR ps
prints a list of all the processes currently running on the system, giving
a line for each process. The process id, process group, tty, user, state,
the kernel code and data segment address of the corresponding binary, the process
heap total and free, overall process memory size, and the process name
and command line are displayed.
.PP
The state is given either as R for running, or S for interruptible sleeping,
s for uninterruptible sleeping, T for stopped, Z for zombie and E for exiting.
The name of the process is taken from its argv[0] as passed to its main function.
.SH EXAMPLES
.IP
ps
.LP
.SH EXIT STATUS
<exit status info>
.TP
.B 0
Process table read successfully.
.TP
.B 1
Unable to accesss 
.I /dev/kmem
or could not read task entries.
.SH FILES
.PD 0
.TP
.B /dev/kmem
.PD
.SH BUGS
This is not really much like real UNIX ps yet.
.SH AUTHORS
Al Riddoch (ajr@ecs.soton.ac.uk)
.br
Greg Haerr (greg@censoft.com)
