#!/usr/bin/env bash
#
# ewcc - OpenWatcom wcc script for ELKS
#
# Usage: ewcc filename.c
#   produces filename.obj
#
# 3 Jun 2024 Compact model only for now
#
set -e

if [ -z "$TOPDIR" ]
  then
    echo "ELKS TOPDIR= environment variable not set"
    exit
fi

if [ -z "$WATCOM" ]
  then
    echo "WATCOM= environment variable not set to compiler path"
    exit
fi

if [ -z "$WATDIR" ]
  then
    echo "WATDIR= environment variable not set to Watcom source directory"
    exit
fi

if [ $# -eq 0 ]
  then
    echo "Usage: ewcc <filename>.c"
    exit
fi

PROG=$1
ELKSLIBCINCLUDE=$TOPDIR/libc/include
ELKSINCLUDE=$TOPDIR/elks/include
WATCINCLUDE=$WATDIR/bld/hdr/dos/h

# -fpmath
# -mabi=cdecl               # push all args
# -msoft-float              # -Wc,-fpc
# -Wc,-fpc                  # soft fp
# -mhard-emu-float          # -Wc,-fpi
# -Wc,-fpi87                # inline 8087 fp
# -Wc,-zev                  # enable void arithmetic
# -std=c99                  # -Wc,-za99
# -fnonconst-initializers   # -Wc,aa

CCFLAGS="\
    -bos2                           \
    -mcmodel=c                      \
    -march=i86                      \
    -std=c99                        \
    -fno-stack-check                \
    -Wc,-wcd=303                    \
    -Wc,-fpi87                      \
    -Wc,-zev                        \
    -fnostdlib                      \
    -I$ELKSLIBCINCLUDE              \
    -I$ELKSINCLUDE                  \
    -I$WATCINCLUDE                  \
    "

owcc -v -c -Wall -Wextra -Os $CCFLAGS -o ${PROG%.c}.obj $PROG

# dump OBJ file
#omfdump ${PROG%.c}.obj

# disassemble OBJ file
#wdis -p -e ${PROG%.c}.obj
