/*
 * For ELKS, NOT generated by mksignames.c
 */

#include "shell.h"

char *const sigmesg[16] = {
      0,
      "Hangup",
      "Interrupt",
      "Quit",
      "Window size change",
      "Stopped",
      "Abort",
      "Terminal Stop",
      "Continue",
      "Killed",
      "User Signal 1",
      "Segmentation fault",
      "Child terminated",
      "Broken pipe",
      "Alarm call",
      "Terminated"
};
