# Basic Makefile, created on Sunday, 09 September 2001 at 09:51:29 BST.
#
# Note that the standard Makefile rules and defines have been moved to
# the file below.

BASEDIR		= ../../../../..

#########################################################################
# Define the variables required by the standard rules - see the standard
# rules file (below) for details of these variables.

USEBCC 	= Y

CLEANDEP	= 

CLEANME 	= 

DEPEND		= 

DISTFILES	= 

#########################################################################
# Include the standard rules.

include $(BASEDIR)/Makefile-rules

#########################################################################
# Specify distribution rule.

distdir:
	cp -pf Makefile keys-*.h $(DISTDIR)/arch/i86/drivers/char/KeyMaps

#########################################################################
### Dependencies:
