.TH CHMOD 1
.SH NAME
chmod \- change access mode for files
.SH SYNOPSIS
\fBchmod \fImode \fIfile\fR ...\fR
.br
.SH EXAMPLES
.TP 20
.B chmod 755 file
Owner: rwx Group: r\-x Others: r\-x.
.SH DESCRIPTION
.PP
The given mode is applied to each file in the file list.
Modes are given as an
octal number that represents the new file mode. The mode bits are defined as
follows: 
.ta 0.25i
.nf
.PP
	4000    Set effective user id on execution to file's owner id
	2000    Set effective group id on execution to file's group id
	0400    file is readable by the owner of the file
	0200    writeable by owner
	0100    executable by owner
	0070    same as above, for other users in the same group
	0007    same as above, for all other users
.PP
.fi
.SH "SEE ALSO"
.BR ls (1),
.BR chmod (2).
