.TH CMP 1
.SH NAME
cmp \- compare two files
.SH SYNOPSIS
\fBcmp\fR \fIfile1 file2\fR
.br
.SH EXAMPLES
.TP 20
.B cmp file1 file2
# Tell whether the files are the same, or print first position of difference.
.SH DESCRIPTION
.PP
Two files are compared. If the files differ, the location
of the first byte of difference is displayed, otherwise
no message is displayed.
.SH EXIT STATUS
.TP 10
.I 0
Files identical
.TP 10
.I 1
Files differ
.TP 10
.I 2
File(s) cannot be opened
.SH "SEE ALSO"
.BR diff (1).
