.TH CMP 1
.SH NAME
cmp \- compare two files
.SH SYNOPSIS
\fBcmp\fR \fIfile1 file2\fR
.br
.SH EXAMPLES
.TP 20
.B cmp file1 file2
Tell whether the files are the same, or print first position of difference.
.SH DESCRIPTION
.PP
Two files are compared.
If they are identical, exit status 0 is returned.
If they differ, exit status 1 is returned.
If the files cannot be opened, exit status 2 is returned.
.SH "SEE ALSO"
.BR diff (1).
