.TH DF 1
.SH NAME
df \- report on free disk space
.SH SYNOPSIS
\fBdf\fP [\fB\-ikP\fP] [\fB\-t\fP \fItype\fP] [\fIfile\fP ...]
.SH DESCRIPTION
.B Df
lists the amount of free space on the currently mounted devices (no arguments),
or the device given as an argument.  If the argument is not a device buf a file or a directory, then the
device it resides on is listed. FAT file systems are supported if the result would 
be meaningful. I.e. not when using the \fB-i\fP or \fB-P\fP options.
.SS OPTIONS
Without options,
.B df
will give a listing like this:
.sp
.nf
Filesystem    1k-Blocks     free     used    %  FUsed%  Mounted on
/dev/hda3         65535    61443     4092   7%     6%   /
/dev/fd0           1440      380     1060  74%    73%   /fd
/dev/hda1        348226   345512     2714   1%          /mnt (FAT)
/dev/hdb1           726      554      172  24%          /mnt5 (FAT)
/dev/hda2         65535    59812     5723   9%     2%   /mnt3
/dev/hda4         41328    37129     4199  11%     3%   /mnt4
.fi
.PP
The
.B \-i
option shifts the focus to inodes:
.sp
.nf
Filesystem       Inodes     IUsed    IFree    %IUsed   Mounted on
/dev/hda3         21845      1187    20658        6%   /
/dev/fd0            256       185       71       73%   /fd
/dev/hdb1     -- Not a MINIX filesystem
/dev/hda2         21845       228    21617        2%   /mnt3
/dev/hda4         13776       313    13463        3%   /mnt4
.fi
.PP
Option
.B \-P
makes
.B df
use \s-2POSIX\s+2 defined output in 512 byte units:
.sp
.nf
Filesystem     512-blocks    Used  Available  Capacity   Mounted on
/dev/hda3        131070      8184   122886        7%     /
/dev/fd0           2880      2120      760       74%     /fd
/dev/hda1     -- Not a MINIX filesystem
/dev/hda2        131070     11446   119624        9%     /mnt3
/dev/hda4         82656      8398    74258       11%     /mnt4
.fi
.PP
With
.B \-k
forces the use of 1024 byte units with the -P option.
.SH BUGS
Default output should also be in 512 byte units says \s-2POSIX\s+2.
Getting data for FAT filesystems is slow.
.SH AUTHOR
Kees J. Bot (kjb@cs.vu.nl)
.SH "SEE ALSO"
.BR du (1).
