.TH kill 1
.SH NAME
kill \- Send a process a signal
.SH SYNOPSIS
.B kill
[\-signal] pid...
.SH DESCRIPTION
.B kill
send a signal to the process specified by each
.I pid
operand listed.
.sp
By default signal 15 (SIGTERM) is
sent.  Process 0 means all the processes in the sender's process group.  A
process  group can be signalled by the negative value of the process group
ID.  Signals may be numerical, or the name of the signal without SIG.
.SH OPTIONS
.TP 20
.I "\-signal"
The signal to be sent. May be HUP, INT QUIT or KILL, or a numeric signal number.
.SH EXAMPLES
.TP 20
.B kill \-HUP 45
Send the HUP signal to process 45.
.TP 20
.B kill \-9 2
Send 9, KILL, to the process with id 2.
.TP 20
.B kill \-INT 4 6 -23
Send the INT signal to
the processes with ids 4 and 6 and the process group with 23.
.SH EXIT STATUS
.TP
.B 0
No invalid arguments specified.
.TP
.B 1
Unknown signal specified, or non-numeric pid specified.
.SH BUGS
Does not support full list of text signal names.
.SH AUTHORS
David I. Bell
.br
Al Riddoch (ajr@ecs.soton.ac.uk) (this manpage)
.SH SEE ALSO
.BR kill (2)
