.TH passwd 1 "ELKS <Whatever>" "ELKS" \" -*- nroff -*-
.SH NAME
passwd \- change user password
.SH SYNOPSIS
.B passwd
[username]
.SH DESCRIPTION
This document describes the ELKS version of
.BR passwd .
This version is extremely minimal and should not be used whenever using a
better version is practical.
.PP
.BR passwd
is used to change the password on user accounts. The super user can change
passwords on any account as specified by
.I username
, whereas ordinary users can only change the password
on their own account.
.SH EXAMPLES
.IP
passwd
.IP
passwd user
.LP
.SH EXIT STATUS
.TP
.B 0
Password changed successfully.
.TP
.B >0
An error occured.
.SH FILES
.PD 0
.TP
.B /etc/passwd
.PD
.SH BUGS
setuid behavoir has not yet been tested.
.SH AUTHORS
Shane Kerr (kerr@wizard.net)
.br
Al Riddoch (ajr@ecs.soton.ac.uk) (this manpage)
.SH SEE ALSO
.BR passwd (5),
.BR getpwent (3),
.BR login (1)
