.TH who 1 "ELKS System Utilities" "ELKS" \" -*- nroff -*-
.SH NAME
who \- show who is logged on
.SH SYNOPSIS
.B who
.SH DESCRIPTION
This document describes the ELKS version of
.BR who .
This version is extremely minimal and should not be used whenever using a
better version is practical.
.PP
.B who
list users currently logged onto the system as recorded in the utmp
file. Each user is displayed as a line containing the username,
the tty name, the time they logged in and information about where
they are logged in from.
.SH EXAMPLES
.IP
who
.LP
.SH EXIT STATUS
.TP
.B 0
.SH FILES
.PD 0
.TP
.B /var/utmp
.TP
.B /etc/passwd
.PD
.SH AUTHORS
Al Riddoch (ajr@ecs.soton.ac.uk)
.SH SEE ALSO
.BR utmp (5)
