# Basic Makefile, created on Sunday, 09 September 2001 at 09:50:19 BST.
#
#########################################################################
#
# Note that the standard Makefile rules and defines have been moved to
# the file below.

BASEDIR		= ../../../..

#########################################################################
# Define the variables required by the standard rules - see the standard
# rules file (below) for details of these variables.

USEBCC 	= N

CLEANDEP	= 

CLEANME 	= 

DEPEND		= 

DISTFILES	= a a.out build

#########################################################################
# Include the standard rules.

include $(BASEDIR)/Makefile-rules

#########################################################################
### Dependencies:
