BEGIN {
	print "// This file is automatically generated from asm-offsets.c";
	print "// See asm-offsets.awk for details\n";
	print "#pragma once\n";
}
/^\tmovw/ {
    print "#define", $3, substr ($2, 2, length ($2) - 2);
}
