.TH HOSTS 5
.SH NAME
hosts \- hostname to IP address database
.SH SYNOPSIS
.B /etc/hosts
.SH DESCRIPTION
The hosts database lists the IP addresses and the hostnames that translate
to these IP addresses. In the absence of name server support on ELKS,
the 
.B hosts
file is used by all network utilities needing name-to-ipaddress translation,
such as
.BR ktcp (8)
and
.BR telnet (1).
.PP
A simple
.B /etc/hosts
may look like this:
.PP
.RS
.ta +15n
.nf
127.0.0.1	localhost
192.168.10.146	imac27
10.0.2.2	server
10.0.2.15	elks15
.fi
.RE
.PP
These entries give names to four IP addresses.  The file may contain
comments marked with '#'.
.PP
You can have aliases (more hostnames on the same line) to give a machine
more than one name, like
.BR www ,
if you run a web server on one.
.PP
.B /etc/hosts
is edited by the 
.BR setup (8)
command which provides a simple way to enable several ELKS systems on a network.
Note that the name and IP-address of the local machine may also be set in the
.I /bootopts
file.

.SH FILES
.nf
/etc/hosts	Hosts database
/bootopts	System configuration file
.fi
.SH "SEE ALSO"
.BR net.cnf (5),
.BR setup (8),
.BR bootopts (5).
