# Basic Makefile, created on Sunday, 09 September 2001 at 09:55:39 BST.
#
# Note that the standard Makefile rules and defines have been moved to
# the file below.

ELKSDIR		= ../..

#########################################################################
# Define the variables required by the standard rules - see the standard
# rules file (below) for details of these variables.

ELKSSTD 	= Y

CLEANDEP	= 

CLEANME 	= 

DEPEND		= 

DISTFILES	= 

#########################################################################
# Include the standard rules.

include $(ELKSDIR)/Makefile-rules

#########################################################################
### Dependencies:
ansi.o: ansi.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h \
 /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h \
 /usr/include/bits/sched.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/string.h

