/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * General setup
 */
#define CONFIG_CONSOLE_DIRECT 1
#define CONFIG_DCON_VT52 1
#undef  CONFIG_DCON_ANSI
#undef  CONFIG_CONSOLE_BIOS
#undef  CONFIG_BE_KEYMAP
#undef  CONFIG_UK_KEYMAP
#undef  CONFIG_ES_KEYMAP
#define CONFIG_DE_KEYMAP 1
#undef  CONFIG_DEFAULT_KEYMAP
#undef  CONFIG_XT
#undef  CONFIG_MODULE
#undef  CONFIG_COMPAQ_FAST
#define CONFIG_CHAR_DEV_MEM 1
#undef  CONFIG_CHAR_DEV_RS
#undef  CONFIG_CHAR_DEV_LP

/*
 * Filesystems
 */
#undef  CONFIG_MINIX_FS
#undef  CONFIG_ROMFS_FS
#define CONFIG_ELKSFS_FS 1
#define CONFIG_FULL_VFS 1
#define CONFIG_PIPE 1
#undef  CONFIG_FS_RO
#define CONFIG_EXEC_MINIX 1
#undef  CONFIG_EXEC_MSDOS

/*
 * Networking
 */
#undef  CONFIG_SOCKET

/*
 * 286 protected mode support
 */
#undef  CONFIG_286PMODE

/*
 * Floppy, IDE, and other block devices
 */
#define CONFIG_BLK_DEV_BIOS 1
#define CONFIG_BLK_DEV_BFD 1
#define CONFIG_BLK_DEV_BHD 1
#undef  CONFIG_BLK_DEV_FD
#undef  CONFIG_BLK_DEV_HD
#undef  CONFIG_DMA
#undef  CONFIG_BLK_DEV_RAM
#undef  CONFIG_BLK_DEV_XD

/*
 * Kernel hacking
 */
#undef  CONFIG_STRACE
#undef  CONFIG_OPT_SMALL
