# Basic Makefile, created on Sunday, 09 September 2001 at 09:53:06 BST.
#
# Note that the standard Makefile rules and defines have been moved to
# the file below.

ELKSDIR		= ../..

#########################################################################
# Variables used by the standard rules.

CLEANME 	= compiler-generated.h

#########################################################################
# Include the standard rules.

include $(ELKSDIR)/Makefile-rules

#########################################################################
### Dependencies:
