;*****************************************************************************
;*
;*                            Open Watcom Project
;*
;*    Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
;*
;*  ========================================================================
;*
;*    This file contains Original Code and/or Modifications of Original
;*    Code as defined in and that are subject to the Sybase Open Watcom
;*    Public License version 1.0 (the 'License'). You may not use this file
;*    except in compliance with the License. BY USING THIS FILE YOU AGREE TO
;*    ALL TERMS AND CONDITIONS OF THE LICENSE. A copy of the License is
;*    provided with the Original Code and Modifications, and is also
;*    available at www.sybase.com/developer/opensource.
;*
;*    The Original Code and all software distributed under the License are
;*    distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
;*    EXPRESS OR IMPLIED, AND SYBASE AND ALL CONTRIBUTORS HEREBY DISCLAIM
;*    ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF
;*    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR
;*    NON-INFRINGEMENT. Please see the License for the specific language
;*    governing rights and limitations under the License.
;*
;*  ========================================================================
;*
;* Description:  WHEN YOU FIGURE OUT WHAT THIS FILE DOES, PLEASE
;*               DESCRIBE IT HERE!
;*
;*****************************************************************************

;
; The following must be in sync with watcom/_mathfun.h
;
FP_FUNC_NULL    equ  0
FP_FUNC_ACOS    equ  1
FP_FUNC_ASIN    equ  2
FP_FUNC_SQRT    equ  3
FP_FUNC_EXP     equ  4
FP_FUNC_COSH    equ  5
FP_FUNC_SINH    equ  6
FP_FUNC_POW     equ  7
FP_FUNC_ACOSH   equ  8
FP_FUNC_LOG2    equ  9
FP_FUNC_LOG     equ  10
FP_FUNC_LOG10   equ  11
FP_FUNC_ATANH   equ  12
FP_FUNC_ATAN2   equ  13
FP_FUNC_IPOW    equ  14
FP_FUNC_DPOWI   equ  15
FP_FUNC_COS     equ  16
FP_FUNC_SIN     equ  17
FP_FUNC_TAN     equ  18
FP_FUNC_Y0      equ  19
FP_FUNC_Y1      equ  20
FP_FUNC_YN      equ  21
FP_FUNC_MOD     equ  22
FP_FUNC_COTAN   equ  23
