#!/bin/sh

MKDEV=/bin/mknod

# RAM disk

$MKDEV ram0 b 1 0
$MKDEV ram1 b 1 1
$MKDEV ram2 b 1 2
$MKDEV ram3 b 1 3
$MKDEV ram4 b 1 4
$MKDEV ram5 b 1 5
$MKDEV ram6 b 1 6
$MKDEV ram7 b 1 7

# BIOS hard disk

$MKDEV bda b 3 0
$MKDEV bda1 b 3 1
$MKDEV bda2 b 3 2
$MKDEV bda3 b 3 3
$MKDEV bda4 b 3 4
$MKDEV bdb b 3 64
$MKDEV bdb1 b 3 65
$MKDEV bdb2 b 3 66
$MKDEV bdb3 b 3 67
$MKDEV bdb4 b 3 68

# BIOS floppy

$MKDEV fd0 b 3 128
$MKDEV fd1 b 3 192

# Direct IDE

$MKDEV hda b 5 0
$MKDEV hda1 b 5 1
$MKDEV hda2 b 5 2
$MKDEV hda3 b 5 3
$MKDEV hda4 b 5 4

$MKDEV hdb b 5 64
$MKDEV hdb1 b 5 65
$MKDEV hdb2 b 5 66
$MKDEV hdb3 b 5 67
$MKDEV hdb4 b 5 68

$MKDEV hdc b 5 128
$MKDEV hdc1 b 5 129
$MKDEV hdc2 b 5 130
$MKDEV hdc3 b 5 131
$MKDEV hdc4 b 5 132

$MKDEV hdd b 5 192
$MKDEV hdd1 b 5 193
$MKDEV hdd2 b 5 194
$MKDEV hdd3 b 5 195
$MKDEV hdd4 b 5 196

# Memory devices

$MKDEV mem c 1 1
$MKDEV kmem c 1 2
$MKDEV null c 1 3
$MKDEV zero c 1 5
$MKDEV full c 1 7

# Virtual consoles

$MKDEV tty1 c 4 0
$MKDEV tty2 c 4 1
$MKDEV tty3 c 4 2

$MKDEV ttys0 c 4 4
$MKDEV ttys1 c 4 5
$MKDEV ttys2 c 4 6
$MKDEV ttys3 c 4 7

# Parallel devices

$MKDEV lp0 c 6 0
$MKDEV lp1 c 6 1
$MKDEV lp2 c 6 2

