#!/bin/bash
#
# This script is used by the `make indent` command, and expects to be called
# with a list of files in the current directory that are NOT to be reindented.
# It reindents all files in the current directory not in that list that match
# the *.c pattern.

export allow_null_glob_expansion=Y

for FILE in *.[ch] ; do \
    if ! printf '%s\n' "$@" | grep -q ^${FILE}'$' ; then
	printf 'Reindenting %s ...\n' "${FILE}" >&2
	if fgrep -q '#asm' "${FILE}" ; then
	    printf "WARNING: %s contains '#asm' statement.\n" "${FILE}" >&2
	fi
	indent "${FILE}" --ignore-profile			\
		--braces-on-if-line				\
		--braces-on-struct-decl-line			\
		--cuddle-else					\
		--dont-break-procedure-type			\
		--else-endif-column24				\
		--indent-level4 				\
		--line-length79 				\
		--no-space-after-function-call-names		\
		--no-space-after-parentheses			\
		--space-after-cast				\
		--start-left-side-of-comments			\
		--tab-size8
    fi
done
