# Basic Makefile, created on Sunday, 09 September 2001 at 09:50:03 BST.
#
# Note that the standard Makefile rules and defines have been moved to
# the file below.

ELKSDIR		= ../../..

include $(ELKSDIR)/Makefile-rules

#########################################################################
# Define rules that are required to be present. Note that if these rules
# have nothing to do, they need to have an action of `@echo -n` defined.

depclean:
	@echo -n

distdir:
	@echo -n

#########################################################################
### Dependencies:
