# Basic Makefile, created on Sunday, 09 September 2001 at 09:55:22 BST.
#
# Note that the standard Makefile rules and defines have been moved to
# the file below.

ELKSDIR		= ../..

#########################################################################
# Define the variables required by the standard rules - see the standard
# rules file (below) for details of these variables.

ELKSSTD 	= Y

CLEANDEP	= 

CLEANME 	= 

DEPEND		= 

DISTFILES	= 

#########################################################################
# Include the standard rules.

include $(ELKSDIR)/Makefile-rules

#########################################################################
### Dependencies:
