BASEDIR=..

include $(BASEDIR)/Make.defs

###############################################################################
#
# Include standard packaging commands.

include $(BASEDIR)/Make.rules

###############################################################################

OBJS = \
	tiny_vfprintf.o \
	# END

all: $(OBJS)

clean:
	rm -f *.o
