#!/bin/bash
#
# Usage:	mktree base dir cmd...
#
#       where	base	is the base directory for the tree to be created,
#		dir	is the path in the said tree, and
#		cmd	is one or more commands to be placed there.
#
###############################################################################
#
# If no commands listed, then just exit - this is NOT an error.

if [ $# -lt 3 ]; then
    exit 0
fi

###############################################################################
#
# Specify the directories to use.

DIR=`echo "$1"/"$2" | tr -s /`
shift 2

###############################################################################
#
# Check they're not non-directories.

if [ -e "${DIR}" -a ! -d "${DIR}" ]; then
    printf '%s: ERROR 1: Not a directory: %s\n' >&2 \
		`basename "$0"` "${DIR}"
    exit 1
fi
if [ "${DIR}" = "/usr/man" ]; then
    for THIS in "${DIR}"/man{1,2,3,4,5,6,7,8,9} ; do
	if [ -e "${THIS}" -a ! -d "${THIS}" ]; then
	    printf '%s: ERROR 2: Not a directory: %s\n' >&2 \
		`basename "$0"` "${THIS}"
	    exit 2
	fi
    done
fi

###############################################################################
#
# Ensure they exist, along with all required parent directories.

if [ "${DIR}" != "/usr/man" ]; then
    mkdir -p "${DIR}"
else
    mkdir -p "${DIR}"/man{1,2,3,4,5,6,7,8,9}
fi

###############################################################################
#
# Function to determine if a particular command has been copied across.

function needed() {
    local X=`echo "$2" | rev | cut -b 3- | rev`

    find $1/../.. -name "$X" > /dev/null
}

###############################################################################
#
# Copy the commands as listed.

if [ "${DIR}" != "/usr/man" -o "$1" != "ALL" ]; then
    for CMD do
	if [ -f "${CMD}" ]; then
	    cp -fv "${CMD}" "${DIR}"
	else
	    printf '%s: WARNING: Skipping missing command: %s\n' >&2 \
		`basename "$0"` "${CMD}"
	fi
    done
else
    for MAN in *.[1-9] . ; do
	if [ -f "${MAN}" ] && needed "${DIR}" "${MAN}" ; then
	    TGT=`echo "${MAN}" | rev | cut -b 1`
	    cp -fv "${MAN}" "${MAN_DIR}"/man${TGT}
	fi
    done
fi

###############################################################################
# EOF #
#######
