#!/bin/bash
#
# Usage:	mktree base dir cmd...
#
#       where	base	is the base directory for the tree to be created,
#		dir	is the path in the said tree, and
#		cmd	is one or more commands to be placed there.
#
###############################################################################
#
# If no commands listed, then just exit - this is NOT an error.

if [ $# -lt 3 ]; then
    exit 0
fi

###############################################################################
#
# Specify the directories to use.

CMD_DIR=`echo "$1"/"$2" | tr -s /`
MAN_DIR=`echo "$1"/usr/man | tr -s /`
shift 2

###############################################################################
#
# Check they're not non-directories.

if [ -e "${CMD_DIR}" -a ! -d "${CMD_DIR}" ]; then
    printf '%s: ERROR 1: Not a directory: %s\n' >&2 \
		`basename "$0"` "${CMD_DIR}"
    exit 1
fi

if [ -e "${MAN_DIR}" -a ! -d "${MAN_DIR}" ]; then
    printf '%s: ERROR 2: Not a directory: %s\n' >&2 \
		`basename "$0"` "${MAN_DIR}"
    exit 2
fi
for DIR in "${MAN_DIR}"/man{1,2,3,4,5,6,7,8,9} ; do
    if [ -e "${DIR}" -a ! -d "${DIR}" ]; then
	printf '%s: ERROR 2: Not a directory: %s\n' >&2 \
		`basename "$0"` "${DIR}"
	exit 2
    fi
done

###############################################################################
#
# Ensure they exist, along with all required parent directories.

mkdir -p "${CMD_DIR}" "${MAN_DIR}"/man{1,2,3,4,5,6,7,8,9}

###############################################################################
#
# Copy the commands as listed.

for CMD do
    if [ -f "${CMD}" ]; then
	cp -fv "${CMD}" "${CMD_DIR}"
	for MAN in "${CMD}".? . ; do
	    if [ -f "${MAN}" ]; then
		TGT=`echo "${MAN}" | rev | cut -b 1`
		cp -fv "${MAN}" "${MAN_DIR}"/man${TGT}
	    fi
	done
    else
	printf '%s: WARNING: Skipping missing command: %s\n' >&2 \
		`basename "$0"` "${CMD}"
    fi
done
