.TH CLOCK 8
.SH NAME
clock \- Read or modify the hardware clock
.SH SYNOPSIS
.B clock
.B [\-u] {\-r,\-w,\-s,\-A}
.SH DESCRIPTION
.BR clock
is used to read from or write to the hardware clock, and to
optionally to set the system clock from the hardware clock.
.SS OPTIONS
.TP
.B "\-u"
The clock is in UTC.
.TP
.B "\-r"
Read the hardware clock.
.TP
.B "\-w"
Write the system time to the hardware clock.
.TP
.B "\-s"
Set the system time from the hardware clock.
.TP
.B "\-A"
Assume AST clock hardware.
.SH EXIT STATUS
.TP
.I 0
Operation completed successfully.
.TP
.I 1
An error occurred.
.TP
.I 2
Not run as superuser.
.SH BUGS
May not run on certain hardware.
.SH AUTHORS
Charles Hedrick (hedrick@cs.rutgers.edu)
.br
Rob Hooft (hooft@chem.ruu.nl)
.br
Harald Koenig (koenig@nova.tat.physik.uni-tuebingen.de)
.br
Alan Modra (alan@spri.levels.unisa.edu.au)
.br
Shane Kerr (kerr@wizard.net)
.br
Al Riddoch (ajr@ecs.soton.ac.uk) (this manpage)
.SH SEE ALSO
.BR date (1),
.BR settimeofday (2),
.BR gettimeofday (2).
