.TH FDISK 8
.SH NAME
fdisk \- create or update a partition table on a hard disk or SSD device
.SH SYNOPSIS
\fBfdisk\fR [\fB\-l\fR] [\fIfile\fR]
.br
.SH OPTIONS
.TP 5
.B \-l
list the partition table and exit.
.SH DESCRIPTION
.PP
When \fBfdisk\fR starts up, it reads in the partition table from 
.BR file ,
or - if no 
.B file
was specified, from the currently booted drive. If the boot drive is a floppy,
.B fdisk
will fail and exit.
.PP
Unless the 
.B -l
option is present, 
.B fdisk
will enter interactive mode and allow the user to manipulate the partition
table using the following commands:
.PP
.nf
	Key Description
	b   Set bootable flag
	d   Delete partition
	l   List partition types
	n   Create new partion
	p   Print partition table
	q   Quit fdisk
	t   Set partition type
	w   Write partition table
	?   Help
.fi
.PP
.B Fdisk
will fail on flat images (disks with no partition table), floppy devices and other devices with no partition. Selecting
.I quit
will discard any changes unless preceeded by the
.I write
command.
.SH EXAMPLES
.TP 10
elks17# \fBfdisk\fP
.nf
Geometry: 7818 cylinders, 16 heads, 63 sectors.
Command (? for help):
.fi
.R Fdisk 
enters interactive mode.
.TP 10
elks17# \fBfdisk -l\fP
.nf
                      START              END          SECTOR
Device      #:ID   Cyl Head Sect    Cyl Head Sect  Start   Size

/dev/hda1  *1:80     0    1    1     66    15   63     63  67473
/dev/hda2   2:80    67    0    1     200   15   63  67536 135072
/dev/hda3   3:00     0    0    0      0    0    0      0      0
/dev/hda4   4:80   332    0    1     432   15   63 7560000 101808
.fi

.B Fdisk 
lists the partition table, the asterisk in the ID-column indictating an active
partition.
.SH BUGS
.PP
.B Fdisk
does minimal sanity checking on input, it is possible to create a totaly bogus partition table.
.SH "SEE ALSO"
.BR part (8).
