.TH FTPD 8 ELKS
.SH NAME
ftpd \- Internet File Transfer Protocol server
.SH SYNOPSIS
.B ftpd
.RB [ \-d ]
.RB [ \-q ]
.RI [ port ]
.SH DESCRIPTION
.I Ftpd
implements the server side of the Internet File Transfer Protocol,
and listens to the standard FTP port # 21, unless otherwise specified on the command line.
.PP
If the 
.B \-d
option is specified,
debugging information is written to the console. Multiple 
.B \-d
options may be specified for increased verbosity level. More than 4 is not meaningful.
.I Ftpd
will normally detach itself from the controlling terminal. If the debug level is 2 or higher, such detach is prevented. 
.PP
If the
.B \-q
option is specified or the variable 
.B QEMU=1 
is found in the environment,
.I ftpd
will assume it is running in the QEMU emulator and remap ports and IP-addresses accordingly.
The mappings correspond with the setup provided for QEMU in the 
.B qemu.sh
script in the ELKS distribution.
.PP
The ftp server
will timeout an inactive session after 15 minutes. (Not yet implemented in ELKS.)
.PP
The ftp server currently supports (or will support) the following ftp
requests; case is not distinguished. The commands marked with a '*' are planned, not implemented.
.PP
.nf
.ta \w'Request        'u
\fBRequest	Description\fP
ABOR*	abort previous command
CDUP*	change to parent of current working directory
CWD	change working directory
DELE	delete a file
HELP	give help information
LIST	give list files in a directory (``ls -lgA'')
MKD	make a directory
NLST	give name list of files in directory 
NOOP	do nothing
PASS	specify password
PASV	set passive mode
PORT	specify data connection port
PWD	print the current working directory
QUIT	terminate session
RETR	retrieve a file
RMD*	remove a directory
SIZE*	return size of file
STAT	return status of server
STOR	store a file
SYST	show operating system type of server system
TYPE	specify data transfer \fItype\fP
USER	specify user name
.fi
.PP
The remaining ftp requests specified in Internet RFC 959 are
reported as unrecognized.
.PP
The ftp server will abort an active file transfer only when the
ABOR command is preceded by a Telnet "Interrupt Process" (IP)
signal and a Telnet "Synch" signal in the command Telnet stream,
as described in Internet RFC 959. (Not yet implemented in ELKS].
.PP
.I Ftpd
interprets file names according to the ``globbing''
conventions used by the ELKS 
.IR sash (1).
This allows users to utilize the metacharacters ``*?[].
.PP
The currrent ELKS-implementation of 
.I ftpd
requires username and password to be specified, but ignores them. 
Future implementations may support authentication via 
.IR /etc/passwd ,
(no null passwords), and 
.IR /etc/ftpusers ,
which contains user names not to be allowed 
.I ftp 
access.
Anonymous authentication is not supported.
.PP
.I Ftpd
implements no securtity measures, and runs from the authenticated user's (currently root) home directory.
CWD to any directory is allowed, which - in combination with the DELETE and RMDIR commands - may be very dangerous.
.SH "SEE ALSO"
ftp(1), ftpget(1), ftpput(1)
.SH BUGS
The lack of security measures makes it easy for inexperienced users to inflict havoc on the system.
