.TH getty 8 "ELKS System Utilities" "ELKS" \" -*- nroff -*-
.SH NAME
getty \- initialise a terminal for login
.SH SYNOPSIS
.B getty
/dev/device [baud]
.SH DESCRIPTION
Copy the /etc/issue file to the terminal, give a login prompt and run login
once a user name has been given.
.P
This version supports the following meta-codes if the configuration variable
SUPER_SMALL has NOT been defined:
.TP
.B @@
The '@' character.
.TP
.B @B
The current Baud rate of the serial port, taken from the command line.
.TP
.B @D
The current date in DD-MMM-YYYY format. 25-Dec-1984 would be an example.
.TP
.B @H
The current system hostname. If /etc/hostname is found, the contents
of its first line are used, otherwise "LocalHost" is assumed.
.TP
.B @L
The current connection identifier, taken from the command line.
.TP
.B @S
The current system type, always "ELKS".
.TP
.B @T
The current system time in 24 hour HH:MM:SS format.
.. .TP
.. .B @U
.. The current number of connected users.
.TP
.B @V
The current kernel version. This is currently fixed during compilation.
.P
Also supported are the standard C escape codes.
.SH EXIT STATUS
.TP
.B 1
Exec of /bin/login failed.
.SH FILES
.TP
.B /bin/login
The program used to complete the login process.
.TP
.B /etc/hostname
The current system hostname.
.TP
.B /etc/issue
The current pre-login message.
.PD
.SH BUGS
Doesn't do most of the stuff normal UNIX getty does yet.
.SH AUTHORS
Al Riddoch (ajr@ecs.soton.ac.uk)
.SH SEE ALSO
.BR login (8)
