.TH login 8
.SH NAME
login \- log on to the system
.SH SYNOPSIS
.B login
[username]
.SH DESCRIPTION
This document describes the ELKS version of
.BR login .
This version is extremely minimal and should not be used whenever using a
better version is practical.
.B login
is used at the beginning of each terminal session to verify that the users
password is entered corrently, to update the utmp file to indicate the
user is logged in, change to the correct user id and group id, initialise
the users environment, change to the users home directory and start the users
shell.
.SS OPTIONS
.TP
.I "[username]"
Log in the user with the given name. If none is specified then a prompt
is printed and a username accepted.
.SH ENVIRONMENT
.B login
does not query the environment, but sets up the following variables:\-
.TP
.SB USER
Set to the users username.
.TP
.SB HOME
Set to the users home directory.
.TP
.SB SHELL
Set to the users shell.
.TP
.SB TERM
Set to the current terminal.
.SH EXIT STATUS
<exit status info>
.TP
.B 1
Failed to log in user.
.SH FILES
.PD 0
.TP
.B /etc/passwd
.TP
.B /var/utmp
.PD
.SH BUGS
The
.SB TERM 
variable is always set to "ansi".
.SH AUTHORS
Al Riddoch (ajr@ecs.soton.ac.uk)
.br
David Murn (scuffer@hups.apana.org.au)
.br
Shane Kerr (kerr@wizard.net)
.SH SEE ALSO
.BR getty (8),
.BR utmp (5)
