'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for mcomp
.\"
.\" Copyright (C), 2003, Luis Bustamante
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the mtools
.\" package
.\"
.\" Mon Mar  3 11:58:15 COT 2003 Luis Bustamante <luferbu@fluidsignal.com>
.\" 
.TH MCOMP 1 "Mon Mar  3 11:58:15 COT 2003" "" "Mtools Users Manual"
.SH NAME
mcomp \- Compares two files using mtools
.SH SYNOPSIS
.\" The command line
.B mcomp
.I file-on-floppy
.I local-file
.SH DESCRIPTION
.B mcomp
compares two files, the first one must be on a floppy disk so it can
be accessed via \fBmtools\fR.
It is not strictly necessary on Debian GNU/Linux, because the diffutils
\fBcmp\fR(1) program provides the same capability after copying the
file locally with

.B mcopy
.I file
.I destination

but this utility is provided in the mtools package for other platforms and 
is retained here for completeness.

.SH AUTHOR
Luis Bustamante <luferbu@fluidsignal.com> wrote this page for the
.I Debian/GNU
mtools package.

.SH "SEE ALSO"
.BR mtools (1),
.BR cmp (1), 
.BR mcopy (1)
