#!/bin/sh

MKDEV=/bin/mknod

# Memory devices

$MKDEV mem c 1 1
$MKDEV kmem c 1 2
$MKDEV null c 1 3
$MKDEV zero c 1 5
$MKDEV full c 1 7

# Virtual consoles

$MKDEV tty1 c 4 0
$MKDEV tty2 c 4 1
$MKDEV tty3 c 4 2

$MKDEV ttys0 c 4 64

#$MKDEV ttyp0 c 4 8
#$MKDEV ttyp1 c 4 9
#$MKDEV ttyp2 c 4 10
#$MKDEV ttyp3 c 4 11
#
#$MKDEV ptyp0 c 2 8
#$MKDEV ptyp1 c 2 9
#$MKDEV ptyp2 c 2 10
#$MKDEV ptyp3 c 2 11

# Parallel devices

#$MKDEV lp0 c 6 0

